### ISSUE TITLE
Two Requests - Meteor and SVG/Vector

### ISSUE THREAD

**Issue by paulmolluzzo** [redradix/posters#1]
These are rad!

Any chance of putting one together for [Meteor](https://www.meteor.com/)? What about including a vector file so they can be scaled or modified?

**Comment by fuzzyalej** [comment]
Hey, thanks for passing by!

We are definitely adding Meteor.js, and we haven't added the vector files yet because we are preparing them :)

**Comment by paulmolluzzo** [comment]
👍

**Comment by fuzzyalej** [comment]
Thanks!

I added a wiki page to add this kind of requests: https://github.com/redradix/posters/wiki

**Comment by fuzzyalej** [comment]
@paulmolluzzo added :)

**Comment by paulmolluzzo** [comment]
Looks rad, and there are vectors! Thanks!
