### ISSUE TITLE
Old io.js logo

### ISSUE THREAD

**Issue by dotproto** [redradix/posters#4]
The io.js logo used in this project is an older version of the current logo. 

https://github.com/iojs/evangelism/blob/master/dashavatars/images/dashavatar-default.png

**Comment by fuzzyalej** [comment]
Thanks @svincent :)
@ChemaRedradix can you try and change the logo, please?

**Comment by ChemaMontero** [comment]
@fuzzyalej Sure, please, remove the old io.js poster ;)
@svincent Thanks a lot!

**Comment by dotproto** [comment]
Happy to help! :smile:

**Comment by fuzzyalej** [comment]
Ready @svincent! :)
